# Generated by Django 5.1 on 2025-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(help_text='Total amount due for payment', verbose_name='Total Amount Owing (PKR)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date (e.g., 2025/11/22)'),
        ),
    ]
