# Generated by Django 5.1 on 2025-10-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_alter_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
    ]
