# Generated by Django 5.1 on 2025-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date (e.g., 2025/11/22)'),
        ),
    ]
